services:
  server:
    container_name: 'server'
    build:
      context: './'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    depends_on:
      database:
        condition: 'service_healthy'
    networks:
      - 'inner'
      - 'outer'
      
  database:
    container_name: 'database'
    build:
      context: '../alakom-db'
      dockerfile: 'Dockerfile'
    healthcheck:
      test: ['CMD', 'sh', '-c', 'pg_restore --verbose --clean --no-acl --no-owner -d Cafedral ../alakom-db/new.sql']
      start_period: '5s'
      interval: '2s'
      timeout: '10s'
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/psql'
    networks:
      - 'inner'

volumes:
  data:
      
networks:
  inner:
  outer:
